# Generated by Django 4.2 on 2024-12-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.CharField(default="general", max_length=100),
        ),
    ]
